### PR TITLE
Add param for the application's environment variable.

### PR DESCRIPTION
**Pull request by rotated8**
Acceptable values are 'development' (the default), and 'production'.

### CODE REVIEW

**Comment by rotated8** [comment]
cc @pmather: Does this seem like a sane approach to keeping Vagrant boxes as dev machines?

**Comment by pmather** [comment]
I think it is worthwhile to try and keep the possibility of supporting both development and production Rails environments in Vagrant.  I believe your approach is as good as any.  I like the fact that it defaults to production, too.

**Comment by pmather** [comment]
:+1: after commit is revised to incorporate suggestion.

**Comment by rotated8** [comment]
Updated!

**Pull request merged**
