### PR TITLE
LIBTD-1449 - Add pull request template

### PR DESCRIPTION
**Pull request by yinlinchen**
Add a PR template for VTUL projects and use this repository as a start.

### CODE REVIEW

**Comment by shabububu** [comment]
Would this the right place to also include other useful information like when to squash commits/comments? If not, where is a good place to put that information? I think it's useful to have conventions documented somewhere so that relatively new folks like me know what normal protocol is.

**Comment by yinlinchen** [comment]
@shabububu You were talking about git workflow, we can create a git workflow document in the confluence.

**Comment by shabububu** [comment]
Are some of the sections optional? Or, are all of them required? That might be useful to note.

**Review by pmather — APPROVED** [review]
The consensus in offline discussion is that this is good to go.

**Pull request merged**
