### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by rotated8**

### CODE REVIEW

**Comment by rotated8** [comment]
- Updates Fedora to 4.5.1
- Updates NodeJS to 6.x
- Updates Ruby to 2.3
- Adds PhantomJS caching for 2.1.1
- Removes Node's old curl-pipe-to-bash install, for a manual approach.

To use the PhantomJS caching, download the tar.bz2 for linux from their website, and put it into the ./files directory.

**Comment by rotated8** [comment]
Fixes #8

**Comment by rotated8** [comment]
Also, a gem handles installing PhantomJS if it is not cached, so it is no longer installed by apt-get.

**Comment by pmather** [comment]
Verified OK. 👍

**Pull request merged**
