### PR TITLE
LIBTD-1655: Allow for carousel package to be specified and unpacked (IAWA)

### PR DESCRIPTION
**Pull request by shabububu**
LIBTD-1655: Allow for carousel package to be specified and unpacked in `{{ project_app_root }}/app/assets/images/vtul/` for IAWA

**JIRA Ticket**: https://webapps.es.vt.edu/jira/browse/LIBTD-1655

# What does this Pull Request do? (:star:)
This PR unpacks a `*.tar.gz` file in `{{ project_app_root }}/app/assets/images/vtul/` for the IAWA homepage carousel.

# What are the changes?
* Adds `carousel_pkg: 'carousel.tar.gz'` to the `example_site_secrets.yml` file to specify the name of a package of images in `ansible/local_files` to be unpacked on the target VM.
* Adds steps for the IAWA role to unpack the images in `{{ project_app_root }}/app/assets/images/vtul/` on the VM.

# How should this be tested?
* Copy `ansible/example_site_secrets.yml` to `ansible/site_secrets.yml`.
* Modify your `ansible/site_secrets.yml` file to include the following:

  ```
  project_name: 'iawa'
  project_git_identifier: 'LIBTD-1655'
  ```

* Copy over the following `carousel.tar.gz` file into your `ansible/local_files/` directory: https://drive.google.com/file/d/1uEocRrf1DA0lm_6ARH6fahrE1Mys1WLb/view?usp=sharing (you'll need to request access)
* Create necessary files: `ansible/local_files/user_list.txt` and `ansible/local_files/admin_list.txt`
* Run `vagrant up` and make sure there are no errors.
* Use `vagrant ssh` to login and switch to the `hydra` user.
* Check that `/var/local/hydra/iawa` contains the `carousel.tar.gz` file.
* Check that `/var/local/hydra/iawa/app/assets/images/vtul/carousel` contains the unzipped contents of the package.
* (optional) Check that the image carousel on the IAWA homepage displays images corresponding to those in the package.
* (optional) Destroy the VM, delete `ansible/local_files/carousel.tar.gz` and try the InstallScripts build again. The build should still be successful. The image carousel on IAWA should still load and display no images for the files that were not unpacked.

# Additional Notes:
* What branch to be used for testing this PR? `LIBTD-1655`
* Additional LIBTD-1655 changes will also be made to the `VTUL/iawa` project.

# Interested parties
@pmather

### CODE REVIEW

**Review by pmather — APPROVED** [review]
These changes work for me.

I've pushed some minor changes that specify ownerships and permissions.

**Comment by shabububu** [comment]
The changes make sense to me. I did a sanity check build, and it looked fine!

**Comment by shabububu** [comment]
I just realized that with these changes, in the rare case that I want to update the images, a vagrant provision will fail update the images with a new package due to permissions.

**Comment by shabububu** [comment]
Opening up the branch again. Code mods + new PR coming soon (from @pmather).

**Pull request merged**
