### PR TITLE
Updates README about Ansible provisioners

### PR DESCRIPTION
**Pull request by rotated8**

### CODE REVIEW

**Comment by rotated8** [comment]
Thanks to @zoto724 for pointing this out.

**Review by pmather — APPROVED** [review]
Technically, "installed"/"not installed" means installed/not installed on the search path.  Ansible may be installed on the system, but if it is not on the search path then it won't be picked up by the `which` command.  Alternatively, you could use "detected to be installed" instead of the word "installed."

**Comment by rotated8** [comment]
@pmather Updated.

**Review by pmather — APPROVED** [review]
That explanation is overly technical if not brutally accurate. 😄

**Pull request merged**
